### ISSUE TITLE
Issue in credit-card-form hypr live file related with expiry year

### ISSUE THREAD

**Issue by sudhirdhumal289** [Mozu/core-theme#4]
I recently pointed out error in /templates/modules/common/credit-card-form.hypr.live file, there is a selection for year 2024 but value of that option is 2023. It should be 2024. This is an issue in both core4 and core5

/templates/modules/common/credit-card-form.hypr.live

option {% if model.expireYear == <b>"2024"</b> %}selected="selected"{% endif %} value=<b>"2023"</b>

**Comment by trent-boyd** [comment]
Looks like this was fixed [sometime last November](https://github.com/Mozu/core-theme/blame/master/templates/modules/common/credit-card-form.hypr.live#L75).

**Comment by sudhirdhumal289** [comment]
Closing as it is not valid anymore.
